// <auto-generated />
using System;
using Bingi_Storage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bingi_Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703005759_ShoppingCartMig2")]
    partial class ShoppingCartMig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bingi_Storage.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublisher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MyAccStatus")
                        .HasColumnType("int");

                    b.Property<int>("MyKycStatus")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OtherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "admin-concurrency-stamp-001",
                            DateOfLastLogin = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            DateOfRegistration = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Email = "edwinnyaluogo@gmail.com",
                            EmailConfirmed = true,
                            IsAdmin = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsPublisher = false,
                            IsSuperAdmin = true,
                            LockoutEnabled = false,
                            MyAccStatus = 0,
                            MyKycStatus = 3,
                            NormalizedEmail = "EDWINNYALUOGO@GMAIL.COM",
                            NormalizedUserName = "ALPHA",
                            PasswordHash = "AQAAAAIAAYagAAAAEOBV6cpmXcJxwJ+mw+fPg4x8aPgKHC9veTzthQGcdqeacsNMFOSjQf45M9Cf7rcNyw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            TwoFactorEnabled = false,
                            UserName = "Alpha"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "user1-concurrency-stamp-001",
                            DateOfLastLogin = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            DateOfRegistration = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Email = "nyabingistudio@proton.me",
                            EmailConfirmed = true,
                            IsAdmin = false,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsPublisher = false,
                            IsSuperAdmin = false,
                            LockoutEnabled = false,
                            MyAccStatus = 0,
                            MyKycStatus = 3,
                            NormalizedEmail = "NYABINGISTUDIO@PROTON.ME",
                            NormalizedUserName = "COMMANDER",
                            PasswordHash = "AQAAAAIAAYagAAAAELSOzm3DdIyV6qYy7JLce6I+HZAB4Wu9yip6c7K0xnl3WN4mTfuLFRk5DQKM764h2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            TwoFactorEnabled = false,
                            UserName = "COMMANDER"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "user2-concurrency-stamp-001",
                            DateOfLastLogin = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            DateOfRegistration = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Email = "user2@bingi.com",
                            EmailConfirmed = true,
                            IsAdmin = false,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsPublisher = false,
                            IsSuperAdmin = false,
                            LockoutEnabled = false,
                            MyAccStatus = 0,
                            MyKycStatus = 3,
                            NormalizedEmail = "USER2@BINGI.COM",
                            NormalizedUserName = "USER2@BINGI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMI+8KKpvzMrq2MQ1WC+9BpylGx5Fqy/LXoucCCaLKeTQdkPRbKrUiNlxeQz766VrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            TwoFactorEnabled = false,
                            UserName = "user2@bingi.com"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e579",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "user3-concurrency-stamp-001",
                            DateOfLastLogin = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            DateOfRegistration = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Email = "user3@bingi.com",
                            EmailConfirmed = true,
                            IsAdmin = false,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            IsPublisher = false,
                            IsSuperAdmin = false,
                            LockoutEnabled = false,
                            MyAccStatus = 0,
                            MyKycStatus = 3,
                            NormalizedEmail = "USER3@BINGI.COM",
                            NormalizedUserName = "USER3@BINGI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENcM3j68sDaodsrHTXxTk3c2KWkafkWe3VEpDl0Ty1B9k76RUUTnU+oLhmEKkDR/Jg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e579",
                            TwoFactorEnabled = false,
                            UserName = "user3@bingi.com"
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BettingEventId")
                        .HasColumnType("int");

                    b.Property<int>("BettingMarketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OddsId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PotentialPayout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BettingEventId");

                    b.HasIndex("BettingMarketId");

                    b.HasIndex("OddsId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("Bingi_Storage.Models.BettingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BettingEvents");
                });

            modelBuilder.Entity("Bingi_Storage.Models.BettingMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BettingMarkets");
                });

            modelBuilder.Entity("Bingi_Storage.Models.BettingOdds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("BettingOdds");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Bundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bundle");
                });

            modelBuilder.Entity("Bingi_Storage.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Bingi_Storage.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Bingi_Storage.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PayType")
                        .HasColumnType("int");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransProvider")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "Pay directly with M-Pesa",
                            IsActive = true,
                            Name = "M-Pesa",
                            PayType = 4,
                            TransProvider = 4,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "Pay with multiple methods via Flutterwave",
                            IsActive = true,
                            Name = "Flutterwave",
                            PayType = 2,
                            TransProvider = 6,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "Pay with cryptocurrency",
                            IsActive = true,
                            Name = "Crypto Wallet",
                            PayType = 3,
                            TransProvider = 9,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "Pay with Airtel Money",
                            IsActive = true,
                            Name = "Airtel Money",
                            PayType = 4,
                            TransProvider = 7,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DefaultPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Documentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ExternalLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FileSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIGen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBettingEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentProductId")
                        .HasColumnType("int");

                    b.Property<int>("PricingState")
                        .HasColumnType("int");

                    b.Property<int>("ProductPublishingStatus")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SuspensionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Version")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VideoTrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://nyabingi.co.ke/index/wp-content/uploads/2025/02/Screenshot-2025-02-18-163014.png",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "BINGIMAN",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://nyabingi.co.ke/index/wp-content/uploads/2025/02/SavageGearsOfficialPoster-1-scaled.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Savage Gears",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://example.com/sample-game.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "BINGIMAN 3",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://example.com/sample-game.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting strategy game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Debe",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://example.com/sample-game.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting racing game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Political Rally",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://nyabingi.co.ke/index/wp-content/uploads/2025/02/Screenshot-2025-02-18-163208.png",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Nafas",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 7,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://example.com/sample-game.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Political Fighter",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 8,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://example.com/sample-game.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Bingivision",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        },
                        new
                        {
                            Id = 9,
                            AgeRestriction = 18,
                            AverageRating = 4.5m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Description = "This is a detailed description of the sample game.",
                            DownloadCount = 1000,
                            FileSize = 5.0m,
                            ImageUrl = "https://example.com/sample-game.jpg",
                            IsAIGen = false,
                            IsBettingEnabled = false,
                            PricingState = 2,
                            ProductPublishingStatus = 0,
                            PublisherId = 1,
                            SalePrice = 29.99m,
                            ShortDescription = "An exciting action game.",
                            SystemRequirements = "Windows 10 or higher",
                            Title = "Armed Rebellion",
                            TotalRatings = 200,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Version = 1.0m
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PareentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PareentCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Action",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Adventure",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Racing",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Strategy",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sport",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Casual",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Software",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMedia");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductPayload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CustomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPublishingStatus")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("_Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPayload");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrice");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PublicityStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<decimal?>("RevenueShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Name = "Nyabingi Studio",
                            PublicityStatus = 1,
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewPublishingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayStatus")
                        .HasColumnType("int");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Bingi_Storage.Models.UserLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("UserLibraries");
                });

            modelBuilder.Entity("Bingi_Storage.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Welcome to Alpha's profile!",
                            Country = "Not specified",
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e576"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Welcome to COMMANDER's profile!",
                            Country = "Not specified",
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Welcome to user2@bingi.com's profile!",
                            Country = "Not specified",
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e578"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Welcome to user3@bingi.com's profile!",
                            Country = "Not specified",
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e579"
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.UserWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WalletStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserWallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Balance = 1000.00m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Currency = "KES",
                            Name = "Alpha's Wallet",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            WalletStatus = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Balance = 500.00m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Currency = "KES",
                            Name = "COMMANDER's Wallet",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            WalletStatus = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Balance = 500.00m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Currency = "KES",
                            Name = "Default Wallet",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            WalletStatus = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Balance = 500.00m,
                            CreatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            Currency = "KES",
                            Name = "Default Wallet",
                            UpdatedAt = new DateTime(2025, 6, 26, 16, 46, 50, 0, DateTimeKind.Utc),
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e579",
                            WalletStatus = 0
                        });
                });

            modelBuilder.Entity("Bingi_Storage.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("BundleProduct", b =>
                {
                    b.Property<int>("BundlesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("BundlesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("BundleProduct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ad376a8f-9eab-4bb9-9fca-30b01540f445",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9344e575"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e579",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlatformProduct", b =>
                {
                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("PlatformsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PlatformProduct");
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductProductCategory");
                });

            modelBuilder.Entity("ProductUserLibrary", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("UserLibraryId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "UserLibraryId");

                    b.HasIndex("UserLibraryId");

                    b.ToTable("ProductUserLibrary");
                });

            modelBuilder.Entity("ProductWishlist", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("ProductWishlist");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Bet", b =>
                {
                    b.HasOne("Bingi_Storage.Models.BettingEvent", "BettingEvent")
                        .WithMany()
                        .HasForeignKey("BettingEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.BettingMarket", "BettingMarket")
                        .WithMany()
                        .HasForeignKey("BettingMarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.BettingOdds", "Odds")
                        .WithMany()
                        .HasForeignKey("OddsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BettingEvent");

                    b.Navigation("BettingMarket");

                    b.Navigation("Odds");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bingi_Storage.Models.CartItem", b =>
                {
                    b.HasOne("Bingi_Storage.Models.ShoppingCart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Order", b =>
                {
                    b.HasOne("Bingi_Storage.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.Transaction", "OrderTransaction")
                        .WithOne("TransactionOrder")
                        .HasForeignKey("Bingi_Storage.Models.Order", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderTransaction");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bingi_Storage.Models.OrderItem", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bingi_Storage.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Product", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", "ParentProduct")
                        .WithMany("ChildProducts")
                        .HasForeignKey("ParentProductId");

                    b.HasOne("Bingi_Storage.Models.Publisher", "Publisher")
                        .WithMany("Products")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentProduct");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductCategory", b =>
                {
                    b.HasOne("Bingi_Storage.Models.ProductCategory", "PareentCategory")
                        .WithMany()
                        .HasForeignKey("PareentCategoryId");

                    b.Navigation("PareentCategory");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductMedia", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", "Product")
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductPayload", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", "Product")
                        .WithMany("Payloads")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ProductPrice", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Publisher", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", "AppUser")
                        .WithOne("Publisher")
                        .HasForeignKey("Bingi_Storage.Models.Publisher", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Review", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ShoppingCart", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Transaction", b =>
                {
                    b.HasOne("Bingi_Storage.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.UserWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Bingi_Storage.Models.UserLibrary", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", "AppUser")
                        .WithOne("Library")
                        .HasForeignKey("Bingi_Storage.Models.UserLibrary", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Bingi_Storage.Models.UserProfile", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Bingi_Storage.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bingi_Storage.Models.UserWallet", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Wishlist", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BundleProduct", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Bundle", null)
                        .WithMany()
                        .HasForeignKey("BundlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Bingi_Storage.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformProduct", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.HasOne("Bingi_Storage.Models.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductUserLibrary", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.UserLibrary", null)
                        .WithMany()
                        .HasForeignKey("UserLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductWishlist", b =>
                {
                    b.HasOne("Bingi_Storage.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingi_Storage.Models.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bingi_Storage.Models.AppUser", b =>
                {
                    b.Navigation("Library");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Product", b =>
                {
                    b.Navigation("ChildProducts");

                    b.Navigation("Media");

                    b.Navigation("Payloads");

                    b.Navigation("Prices");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Publisher", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Bingi_Storage.Models.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Bingi_Storage.Models.Transaction", b =>
                {
                    b.Navigation("TransactionOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
